### PR TITLE
Declare IntercomAPI to prevent TypeScript warning

### PR DESCRIPTION
**Pull request by thomaswangio**
Warning - 

```
ts] Module '"/node_modules/react-intercom/index"' has no exported member 'IntercomAPI'.
```

### CODE REVIEW

**Comment by thomaswangio** [comment]
Also, typo in description, should be: "A component to configure and enable Intercom in your react application"

**Comment by AnthonyLenglet** [comment]
to anyone getting this issue, the current solution is to keep the version to 1.0.14, the index.d.ts causing the issue wasn't added before then

**Comment by kubk** [comment]
@nhagen Any chances to get this merged?

**Comment by jpbow** [comment]
For anyone still running into this warning (I'm using 1.0.15), just create a `react-intercom.d.ts` file inside of an @types folder in your project root and copy-paste the following declaration. It cleared up the warning for me.
```
declare module "react-intercom" {
  export function IntercomAPI(method: string, ...args: Array<any>): void;
}
```

**Pull request closed without merging**
